import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const runlife = localFont({
  src: "../public/fonts/Runlife-Regular.woff2",
  variable: "--font-runlife",
  display: "swap",
});

const UTScript = localFont({
  src: "../public/fonts/UTMynabaliScript.woff",
  variable: "--font-utscript",
  display: "swap",
});

const gloria = localFont({
  src: "../public/fonts/GloriaRocha.woff",
  variable: "--font-gloria",
  display: "swap",
});

const rekalgera = localFont({
  src: "../public/fonts/Rekalgera-Regular.woff",
  variable: "--font-rekalgera",
  display: "swap",
});

const prestiblack = localFont({
  src: "../public/fonts/PrestiDisplay-Black.woff",
  variable: "--font-prestiblack",
  display: "swap",
});

const prestiregular = localFont({
  src: "../public/fonts/PrestiDisplay-Regular.woff",
  variable: "--font-prestiregular",
  display: "swap",
});

const prestisemibold = localFont({
  src: "../public/fonts/PrestiDisplay-Semibold.woff",
  variable: "--font-prestisemibold",
  display: "swap",
});

const prestibold = localFont({
  src: "../public/fonts/PrestiDisplay-Bold.woff",
  variable: "--font-prestibold",
  display: "swap",
});

const hopelessromantic = localFont({
  src: "../public/fonts/HopelessRomanticSociety.woff",
  variable: "--font-hopeless-romantic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${prestibold.variable} ${geistMono.variable} ${runlife.variable} ${gloria.variable} ${UTScript.variable} ${rekalgera.variable} ${prestiblack.variable} ${prestiregular.variable} ${prestisemibold.variable} ${hopelessromantic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
